language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - /v\d+\.\d+/
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
after_script:
  - npx codecov
notifications:
  email: false
deploy:
  provider: npm
  email: notcaseywebb@gmail.com
  api_key:
    secure: d14s5MZeL7XWiFVuftZcSLtbLPzmCm29qeMgGfNdjOLtAwutYI8tfdSVj5ZsZemaGzsDp+KNDWUukASVUbPvx10XLEPLq/oJyUDnyi2oKbMTllaJA/ApiJiqcGkEvKv8LmFn38Lmq9Nr/mD0uiUaBQ692PkfeKx7QS8Z0LyraIXQD3QUbh35Q9bKMSFV/Yt1HidHUCSpOD2AeNW/+SxRT1MbyKxdWJpki1/q54/XsUjpm69A8G0k96Sdzg+GBJoj17/+XBPyrHwUxfd81ClZc2gCQTkR/5Xbs5pJD9BzBTmitpIzxXP8hvG9q+x7qm1jCGp29EcBb37rVAfKrz5e9Gmj6yk+ZtvuNkvxSTLqXXQQIXJclulW1u/HYn++HEvEvR19U7ZLy5llaN1L1J5ullwUQzGDu1H7Hwhanah0eOB5a8vJEX3NqUG8BY+EHFG2SlcXTjnGExVnRkG22oKVWD4ZzCov0uy+yVkcxJx01XbEckf10Rd4zPvEKQ+3hSDqOW1w5PccFTYqI8iU0K0CjoJpdnSjA6q7d2A+GbJuPPQxz5ekJKq6+TEjTGr+SbP5+Vc/psHV12NsqVqw36SC72xCMTEdX3aCDksDl0yZqwAEfCvQhEmUIYbiMfIotPBar3Zk1A1iDCMYq9XPiGOcjEXlT87XWCPGDMPTBvgbctE=
  on:
    tags: true
    repo: caseyWebb/ghmenu
